---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-registry-deployment
  labels:
    app: docker-registry
spec:
  replicas: 2
  selector:
    matchLabels:
      app: docker-registry
  template:
    metadata:
      labels:
        app: docker-registry
    spec:
      volumes:
        - name: docker-registry-storage
          persistentVolumeClaim:
            claimName: docker-registry-pvc
        - name: secret-volume
          secret:
            secretName: registry-certs-keys
        - name: auth-volume
          secret:
            secretName: registry-htpasswd
        - name: config
          configMap:
            name: registry-config
            items:
              - key: registry-config
                path: config.yml
      containers:
        - name: registry
          image: registry:2
          ports:
            - name: http
              containerPort: 5000
          volumeMounts:
            - name: docker-registry-storage
              mountPath: /var/lib/registry
            - mountPath: /certs
              name: secret-volume
            - mountPath: /auth
              name: auth-volume
            - name: config
              mountPath: /etc/docker/registry/
