---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: docker-registry-gc
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          volumes:
            - name: docker-registry-storage
              persistentVolumeClaim:
                claimName: docker-registry-pvc

          containers:
            - name: registry-gc
              image: registry:2
              env:
                - name: REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY
                  value: "/var/lib/registry"
                - name: REGISTRY_AUTH
                  value: "htpasswd"
              imagePullPolicy: IfNotPresent
              command:
                - /bin/sh
                - -c
                - registry garbage-collect /etc/docker/registry/config.yml
              volumeMounts:
                - name: docker-registry-storage
                  mountPath: /var/lib/registry
          restartPolicy: OnFailure
