apiVersion: batch/v1
kind: CronJob
metadata:
  name: docker-registry-gc
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
            containers:
            - name: registry-gc
              image: registry:2
              env:
              - name: REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY
                value: "/var/lib/registry"
              imagePullPolicy: IfNotPresent
              command:
                - /bin/sh
                - -c
                - registry garbage-collect /etc/docker/registry/config.yml
              volumeMounts:
              - name: docker-registry-storage
                mountPath: /var/lib/registry
            volumes:
            - name: docker-registry-storage
              persistentVolumeClaim:
                claimName: docker-registry-pvc
            restartPolicy: OnFailure