---
apiVersion: v1
kind: ConfigMap
metadata:
  name: registry-config
data:
  registry-config: |
    version: 0.1
    log:
      fields:
        service: registry
    storage:
      delete:
        enabled: true
      cache:
        blobdescriptor: redis
      filesystem:
        rootdirectory: /var/lib/registry
    http:
      addr: :5000
      secret: asecretforlocaldevelopment
      headers:
        X-Content-Type-Options: [nosniff]
      debug:
        addr: :5001
        prometheus:
          enabled: true
          path: /metrics
    health:
      storagedriver:
        enabled: true
        interval: 10s
        threshold: 3
    redis:
      addr: 10.104.252.203:6379
      db: 0
      pool:
        maxidle: 16
        maxactive: 64
        idletimeout: 300s
