apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: default
spec:
  containers:
  - image: busybox
    command:
    - sleep
    - "3600"
    imagePullPolicy: IfNotPresent
    name: busybox

    volumeMounts:
    - name: docker-registry-storage # Test to see if another pod on same node can access the shared pvc
      mountPath: /data
  restartPolicy: Always
  volumes:
    - name: docker-registry-storage
      persistentVolumeClaim:
        claimName: docker-registry-pvc
