#!/usr/bin/env bash

set -ex

# Filter Golang files match Added (A), Copied (C), Modified (M) conditions.
ymlfiles=$(git diff --cached --name-only --diff-filter=ACM | grep '\.yml$\|\.yaml$' || true)

if [ -n "$ymlfiles" ]; then
    yamllint -s -w $ymlfiles
fi

